import {
  FaFileAlt,
  FaBriefcase,
  FaBuilding,
  FaPhoneAlt,
  FaAmbulance,
  FaCity,
  FaCogs,
  FaGasPump,
  FaWater,
  FaPhone,
  FaEnvelope,
  FaBox,
  FaHandsHelping,
  FaUniversity,
  FaLaptop,
  FaUserTie,
  FaHospital,
  FaUserMd,
  FaStethoscope,
  FaSchool,
  FaChalkboardTeacher,
  FaUsers,
  FaMosque,
  FaBookReader,
  FaTrafficLight,
  FaRunning,
  FaBlind,
  FaDeaf,
  FaGraduationCap,
  FaGavel,
  FaBalanceScale,
  FaLeaf,
  FaPassport,
  FaFlag,
  FaTrain,
  FaGlobe,
  FaLandmark,
  FaSeedling,
  FaHome,
  FaToolbox,
  FaShieldAlt,
  FaBug,
  FaSubway,
  FaClipboardList,
  FaUtensils,
} from "react-icons/fa";

export default Object.freeze({
  ProviderData: [
    {
      name: "Civil Status Sector",
      text: "Providing civil status services.",
      icons: [<FaBuilding />, <FaPhoneAlt />],
    },
    {
      name: "Health Office",
      text: "Providing health services to the community.",
      icons: [<FaBuilding />, <FaAmbulance />],
    },
    {
      name: "Ministry of Health and Population",
      text: "Government body responsible for health services.",
      icons: [<FaBuilding />, <FaAmbulance />],
    },
    {
      name: "Governorate/Technological Center",
      text: "Serving as a technological hub for governance.",
      icons: [<FaBuilding />, <FaPhoneAlt />],
    },
    {
      name: "City Authority",
      text: "Managing city services and infrastructure.",
      icons: [<FaCity />, <FaBuilding />],
    },
    {
      name: "Local Administrative Units",
      text: "Local governance and community support.",
      icons: [<FaCogs />, <FaUsers />],
    },
    {
      name: "Real Estate Registration and Documentation Authority",
      text: "Managing real estate documentation and registration.",
      icons: [<FaFileAlt />, <FaBuilding />],
    },
    {
      name: "Cairo",
      text: "Capital city of Egypt.",
      icons: [<FaCity />],
    },
    {
      name: "Gas Company (EGAS)",
      text: "Providing natural gas services.",
      icons: [<FaGasPump />],
    },
    {
      name: "Water Company",
      text: "Supplying water services.",
      icons: [<FaWater />],
    },
    {
      name: "Central (Telephone Exchange)",
      text: "Providing telecommunication services.",
      icons: [<FaPhoneAlt />],
    },
    {
      name: "Egyptian Telecommunications Company",
      text: "Telecommunications and internet services.",
      icons: [<FaPhone />],
    },
    {
      name: "Post Office",
      text: "Postal and courier services.",
      icons: [<FaEnvelope />],
    },
    {
      name: "Supply Office",
      text: "Managing supply and procurement services.",
      icons: [<FaBox />],
    },
    {
      name: "Directorate of Social Solidarity",
      text: "Providing social welfare programs.",
      icons: [<FaHandsHelping />],
    },
    {
      name: "Nasser Social Bank",
      text: "Bank providing social development loans.",
      icons: [<FaUniversity />],
    },
    {
      name: "Directorate of Labor",
      text: "Regulating labor laws and services.",
      icons: [<FaBriefcase />],
    },
    {
      name: "Government Portal",
      text: "Centralized government information platform.",
      icons: [<FaLaptop />],
    },
    {
      name: "Labor Office",
      text: "Employment services and job registration.",
      icons: [<FaUserTie />],
    },
    {
      name: "Directorate of Health Affairs",
      text: "Managing health services and facilities.",
      icons: [<FaHospital />],
    },
    {
      name: "Ministry of Labor",
      text: "Overseeing labor and employment services.",
      icons: [<FaBriefcase />],
    },
    {
      name: "Egyptian Ambulance Authority",
      text: "Emergency medical and ambulance services.",
      icons: [<FaAmbulance />],
    },
    {
      name: "General Authority for Health Insurance",
      text: "Health insurance services and coverage.",
      icons: [<FaUserMd />],
    },
    {
      name: "Medical Council of the Governorate",
      text: "Overseeing medical professionals and services.",
      icons: [<FaStethoscope />],
    },
    {
      name: "School",
      text: "Providing educational services.",
      icons: [<FaSchool />],
    },
    {
      name: "Educational Administration",
      text: "Managing educational institutions and programs.",
      icons: [<FaChalkboardTeacher />],
    },
    {
      name: "General Administration for Community Education",
      text: "Promoting community-based education.",
      icons: [<FaUsers />],
    },
    {
      name: "Sector of Al-Azhar Institutes",
      text: "Managing Islamic education institutions.",
      icons: [<FaMosque />],
    },
    {
      name: "Directorate of Education",
      text: "Providing educational services at the regional level.",
      icons: [<FaSchool />],
    },
    {
      name: "General Authority for Illiteracy Eradication and Adult Education",
      text: "Promoting literacy and adult education programs.",
      icons: [<FaBookReader />],
    },

    {
      name: "Ministry of Education Website",
      text: "Official platform for educational services.",
      icons: [<FaSchool />],
    },
    {
      name: "General Traffic Department",
      text: "Traffic regulations and licensing services.",
      icons: [<FaTrafficLight />],
    },
    {
      name: "Youth and Sports Directorate",
      text: "Providing sports and youth activities.",
      icons: [<FaRunning />],
    },
    {
      name: "Ministry of Social Solidarity",
      text: "Social protection and assistance services.",
      icons: [<FaHandsHelping />],
    },
    {
      name: "Al Noor School for the Blind",
      text: "Specialized school for visually impaired students.",
      icons: [<FaBlind />],
    },
    {
      name: "Al Amal School for the Deaf",
      text: "Educational support for deaf students.",
      icons: [<FaDeaf />],
    },
    {
      name: "School for Hearing-Impaired",
      text: "Support and education for hearing-impaired students.",
      icons: [<FaGraduationCap />],
    },
    {
      name: "Intellectual Education Schools",
      text: "Education for children with intellectual challenges.",
      icons: [<FaUniversity />],
    },
    {
      name: "Workers' Fund for Public and Private Sectors",
      text: "Support fund for sector employees.",
      icons: [<FaHandsHelping />],
    },
    {
      name: "Defense Ministry Pension and Insurance",
      text: "Insurance services for armed forces personnel.",
      icons: [<FaFlag />],
    },
    {
      name: "Primary Courts",
      text: "Judicial services and legal proceedings.",
      icons: [<FaGavel />],
    },
    {
      name: "Appeals Courts",
      text: "Handling cases for appeals and disputes.",
      icons: [<FaBalanceScale />],
    },
    {
      name: "Environmental Affairs Agency",
      text: "Environmental regulation and preservation.",
      icons: [<FaLeaf />],
    },
    {
      name: "Real Estate Tax Directorate",
      text: "Managing real estate tax collection.",
      icons: [<FaLeaf />],
    },
    {
      name: "Egyptian Tax Authority",
      text: "Administration of national taxes.",
      icons: [<FaLeaf />],
    },
    {
      name: "Passport, Immigration, and Nationality Authority",
      text: "Issuance and management of passports.",
      icons: [<FaPassport />],
    },
    {
      name: "Recruitment and Mobilization Authority",
      text: "Military conscription management.",
      icons: [<FaFlag />],
    },
    {
      name: "Railway Authority Portal",
      text: "Information and ticket booking services.",
      icons: [<FaTrain />],
    },
    {
      name: "General Work Permit Department",
      text: "Issuance of work permits.",
      icons: [<FaToolbox />],
    },
    {
      name: "General Secondary Coordination Portal",
      text: "University admission coordination.",
      icons: [<FaGraduationCap />],
    },
    {
      name: "Coordination Office",
      text: "Higher education admission services.",
      icons: [<FaUniversity />],
    },
    {
      name: "Supreme Council of Universities",
      text: "Policy coordination for higher education.",
      icons: [<FaLandmark />],
    },
    {
      name: "General Traffic Department (Ministry of Justice)",
      text: "Judicial oversight of traffic services.",
      icons: [<FaTrafficLight />],
    },
    {
      name: "Egyptian General Drainage Projects Authority",
      text: "Managing national drainage projects.",
      icons: [<FaWater />],
    },
    {
      name: "Irrigation Authority",
      text: "Water resource management.",
      icons: [<FaWater />],
    },
    {
      name: "Agricultural Budget Fund Authority",
      text: "Supporting agricultural development.",
      icons: [<FaSeedling />],
    },
    {
      name: "Groundwater Department",
      text: "Managing groundwater resources.",
      icons: [<FaGlobe />],
    },
    {
      name: "Land Improvement Projects Executive Agency",
      text: "Land development initiatives.",
      icons: [<FaBox />],
    },
    {
      name: "General Administrative Affairs Department",
      text: "Handling internal administrative tasks.",
      icons: [<FaHome />],
    },
    {
      name: "Social Development Fund",
      text: "Financial and social support services.",
      icons: [<FaHandsHelping />],
    },
    {
      name: "Social Rehabilitation Office",
      text: "Providing social support and rehabilitation services.",
      icons: [<FaUsers />],
    },
    {
      name: "Egyptian Company for Metro Operation",
      text: "Management and operation of the metro system.",
      icons: [<FaSubway />],
    },
    {
      name: "New Fardous City",
      text: "Urban development and residential projects.",
      icons: [<FaCity />],
    },
    {
      name: "Public Security Sector - Forensic Investigation Department",
      text: "Forensic evidence collection and investigations.",
      icons: [<FaShieldAlt />],
    },
    {
      name: "Public Security Sector - Licensing Department",
      text: "Issuance and management of various licenses.",
      icons: [<FaClipboardList />],
    },
    {
      name: "Public Security Sector",
      text: "General public security services.",
      icons: [<FaShieldAlt />],
    },
    {
      name: "Central Pest Control Department",
      text: "Control and prevention of agricultural pests.",
      icons: [<FaBug />],
    },
    {
      name: "Regional Center for Food and Feed",
      text: "Research and monitoring of food and animal feed quality.",
      icons: [<FaUtensils />],
    },
  ],
});
