"Civil Status Sector";
"Health Office";
"Ministry of Health and Population";
"Governorate/Technological Center";
"City Authority";
"Local Administrative Units";
"Real Estate Registration and Documentation Authority";
"Cairo";
"Gas Company (EGAS)";
"Water Company";
"Central (Telephone Exchange)";
"Egyptian Telecommunications Company";
"Post Office";
"Supply Office";
"Directorate of Social Solidarity";
"Nasser Social Bank";
"Directorate of Labor";
"Government Portal";
"Labor Office";
"Directorate of Health Affairs";
"Ministry of Labor";
"Egyptian Ambulance Authority";
"General Authority for Health Insurance";
"Medical Council of the Governorate";
"School";
"Educational Administration";
"General Administration for Community Education";
"Sector of Al-Azhar Institutes";
"Directorate of Education";
"General Authority for Illiteracy Eradication and Adult Education";
"Ministry of Education Website";
"General Traffic Department";
"Youth and Sports Directorate";
"Ministry of Social Solidarity";
"Al Noor School for the Blind";
"Al Amal School for the Deaf";
"School for Hearing-Impaired";
"Intellectual Education Schools";
"Workers' Fund for Public and Private Sectors";
"Defense Ministry Pension and Insurance";
"Primary Courts";
"Appeals Courts";
"Environmental Affairs Agency";
"Real Estate Tax Directorate";
"Egyptian Tax Authority";
"Passport, Immigration, and Nationality Authority";
"Recruitment and Mobilization Authority";
"Railway Authority Portal";
"General Work Permit Department";
"General Secondary Coordination Portal";
"Coordination Office";
"Supreme Council of Universities";
"General Traffic Department (Ministry of Justice)";
"Egyptian General Drainage Projects Authority";
"Irrigation Authority";
"Agricultural Budget Fund Authority";
"Groundwater Department";
"Land Improvement Projects Executive Agency";
"General Administrative Affairs Department";
"Social Development Fund";
"Social Rehabilitation Office";
"Egyptian Company for Metro Operation";
"New Fardous City";
"Public Security Sector - Forensic Investigation Department";
"Public Security Sector - Licensing Department";
"Public Security Sector";
"Central Pest Control Department";
"Regional Center for Food and Feed";
